[ClassVersion("1.0"), FriendlyName("rsCertificateStore")]
class RS_rsCertificateStore : OMI_BaseResource
{
[Key, Description("Name or Thumbprint of Certificate")] String Name;
[write, Description("Location of Certificate or PFX file for installation")] String Path;
[write,ValueMap{"LocalMachine", "CurrentUser"},Values{"LocalMachine", "CurrentUser"}] String Location;
[write, Description("Certificate Stores to place certificate in.")] String Store[];
[write, Description("plaintext password for PFX file.")] String Password;
[write, Description("Secure password for PFX file."),EmbeddedInstance("MSFT_Credential")] String SecurePassword;
[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
